// SPDX-FileCopyrightText: 2026 Thai Embedded Systems Association (TESA)
// SPDX-License-Identifier: Apache-2.0
//
// Starlight's docs collection. Pages in src/content/docs/ are GENERATED by
// scripts/sync_content.py; our own lesson metadata rides in the namespaced `tqp` field
// (lesson header, review questions, citation) so Starlight's own fields stay untouched.
import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { docsLoader } from '@astrojs/starlight/loaders';
import { docsSchema } from '@astrojs/starlight/schema';

export const collections = {
	docs: defineCollection({
		loader: docsLoader(),
		schema: docsSchema({
			extend: z.object({
				tqp: z.record(z.string(), z.unknown()).optional(),
			}),
		}),
	}),
};
