#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Thai Embedded Systems Association (TESA)
# SPDX-License-Identifier: Apache-2.0
"""Build CREDITS.md at the repo root from courses/*/credits.yaml.

    python3 tools/gen_credits.py           # (re)write CREDITS.md
    python3 tools/gen_credits.py --check   # exit 1 if CREDITS.md is missing or stale

CC BY and CC BY-SA require the attribution to travel with the work, so every third-party image
a course ships is listed here with title, author, source, licence and whether it was modified.
Courses appear in catalog order. The output has no timestamp: the same credits give the same
bytes, which is what makes --check meaningful in CI.
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import REPO_ROOT, iter_course_dirs, load_yaml  # noqa: E402

OUT_NAME = "CREDITS.md"


def _cell(v) -> str:
    s = "" if v is None else str(v)
    return " ".join(s.split()).replace("|", "\\|")


def _modified(v) -> str:
    if v is True:
        return "ดัดแปลง · modified"
    if v in (False, None, ""):
        return "ไม่ดัดแปลง · unmodified"
    return _cell(v)


def _course_order(root: Path) -> tuple[list[str], dict[str, dict]]:
    doc = load_yaml(root / "catalog" / "courses.yaml")
    entries = {}
    order = []
    if not doc.error and isinstance(doc.data, dict):
        for c in doc.data.get("courses") or []:
            if isinstance(c, dict) and isinstance(c.get("id"), str):
                order.append(c["id"])
                entries[c["id"]] = c
    return order, entries


def render(root: Path) -> tuple[str, list[str]]:
    """(CREDITS.md text, problems). Problems are unreadable credits files."""
    order, entries = _course_order(root)
    problems: list[str] = []
    sections: dict[str, list[dict]] = {}
    titles: dict[str, str] = {}
    for cdir in iter_course_dirs(root):
        path = cdir / "credits.yaml"
        if not path.is_file():
            continue
        doc = load_yaml(path)
        if doc.error or not isinstance(doc.data, dict):
            problems.append(f"courses/{cdir.name}/credits.yaml: {doc.error or 'not a mapping'}")
            continue
        images = [im for im in (doc.data.get("images") or []) if isinstance(im, dict)]
        if images:
            sections[cdir.name] = sorted(images, key=lambda im: str(im.get("path", "")))
        cy = load_yaml(cdir / "course.yaml")
        t = (cy.data or {}).get("title") if not cy.error and isinstance(cy.data, dict) else None
        t = t or entries.get(cdir.name, {}).get("title") or {}
        titles[cdir.name] = (t.get("th") or t.get("en") or cdir.name) if isinstance(t, dict) else cdir.name
    ids = [c for c in order if c in sections] + sorted(c for c in sections if c not in order)
    total = sum(len(v) for v in sections.values())
    lines = [
        "<!-- GENERATED by tools/gen_credits.py from courses/*/credits.yaml. Do not edit by hand: "
        "edit the course's credits.yaml and run `python3 tools/gen_credits.py`. -->",
        "",
        "# เครดิตสื่อจากบุคคลที่สาม · Third-party credits",
        "",
        "ภาพและสื่อจากบุคคลที่สามที่หลักสูตรใน TESA Open Knowledge ใช้ พร้อมผู้สร้าง แหล่งที่มา และสัญญาอนุญาต "
        "แต่ละรายการยังคงสัญญาอนุญาตเดิมของเจ้าของ เนื้อหาส่วนอื่นเผยแพร่ตามที่ระบุใน [REUSE.toml](REUSE.toml)",
        "",
        "Third-party images and media used by the TESA Open Knowledge courses, with author, source and "
        "licence. Each item keeps its owner's licence; everything else is licensed as stated in "
        "[REUSE.toml](REUSE.toml).",
        "",
        "- การอ้างอิงต้นฉบับที่ดัดแปลงมา (รศ.วิรุฬห์ ศรีบริรักษ์ BUU/AIC, ผศ.ดร.สันติ นุราช KMUTT, Meysam Parvizi, Infineon) อยู่ใน [NOTICE.md](NOTICE.md) · "
        "Upstream attributions: [NOTICE.md](NOTICE.md)",
        "- วิธีให้เครดิต TESA เมื่อนำไปใช้ต่อ อยู่ใน [ATTRIBUTION.md](ATTRIBUTION.md) · "
        "How to credit TESA when you reuse this material: [ATTRIBUTION.md](ATTRIBUTION.md)",
        "",
        f"รวม {total} รายการ จาก {len(ids)} หลักสูตร · {total} item(s) from {len(ids)} course(s).",
    ]
    if not ids:
        lines += ["", "_ยังไม่มีสื่อจากบุคคลที่สาม · No third-party media yet._"]
    for cid in ids:
        lines += ["", f"## {_cell(titles.get(cid, cid))} (`{cid}`)", "",
                  "| ไฟล์ · File | ชื่อ · Title | ผู้สร้าง · Author | แหล่งที่มา · Source | "
                  "สัญญาอนุญาต · Licence | การดัดแปลง · Changes |",
                  "|---|---|---|---|---|---|"]
        for im in sections[cid]:
            p = str(im.get("path", ""))
            src = im.get("source")
            src_md = f"[{_cell(src)}]({src})" if src else ""
            lines.append(f"| [`{_cell(p)}`](courses/{cid}/{p}) | {_cell(im.get('title'))} | "
                         f"{_cell(im.get('author'))} | {src_md} | {_cell(im.get('license'))} | "
                         f"{_modified(im.get('modified'))} |")
    return "\n".join(lines) + "\n", problems


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--root", default=str(REPO_ROOT), help="repository root (default: this repo)")
    ap.add_argument("--check", action="store_true", help="exit 1 if CREDITS.md is missing or stale")
    ns = ap.parse_args(argv)
    root = Path(ns.root).resolve()
    text, problems = render(root)
    for p in problems:
        print(f"gen_credits: {p}", file=sys.stderr)
    out = root / OUT_NAME
    if ns.check:
        current = out.read_text(encoding="utf-8") if out.is_file() else ""
        if current != text:
            print(f"gen_credits: {OUT_NAME} is {'stale' if current else 'missing'} — run "
                  "`python3 tools/gen_credits.py` and commit the result", file=sys.stderr)
            sys.stderr.writelines(list(difflib.unified_diff(
                current.splitlines(keepends=True), text.splitlines(keepends=True),
                f"{OUT_NAME} (committed)", f"{OUT_NAME} (generated)", n=1))[:60])
            return 1
        print(f"gen_credits: {OUT_NAME} is up to date")
        return 1 if problems else 0
    if not out.is_file() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
        print(f"gen_credits: wrote {OUT_NAME}")
    else:
        print(f"gen_credits: {OUT_NAME} unchanged")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
